language: dart
dart:
  - "dev/release/1.25.0-dev.11.0"
sudo: false
before_script:
  - ./travis/setup.sh
script:
  - ./travis/build.sh
  - ./travis/test.sh
  - ./travis/format.sh

# We don't build the engine or run the tests for the engine on Travis
# See testing/run_tests.sh if that's what you're looking for though.
